'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApp1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _360_F_639506337_9LQK7W4jkmCixMk1TQ6rgYOW0jsHiH0N() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("360_F_639506337_9LQK7W4jkmCixMk1TQ6rgYOW0jsHiH0N", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _360_F_639506337_9LQK7W4jkmCixMk1TQ6rgYOW0jsHiH0N1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("360_F_639506337_9LQK7W4jkmCixMk1TQ6rgYOW0jsHiH0N1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _360_F_99905255_nSm85vHjPzL7Pg4dWKiXUDmtHZIUBQyo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("360_F_99905255_nSm85vHjPzL7Pg4dWKiXUDmtHZIUBQyo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _41473182() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("41473182", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _414731821() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("414731821", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property abstract_health_medical_science_healthcare_icon_digital_technology_doctor_concept_modern_innovation_treatment_medicine_on_hi_tech_future_blue_background_for_wallpaper_template_web_design_vector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract-health-medical-science-healthcare-icon-digital-technology-doctor-concept"& _ 
                        "-modern-innovation-treatment-medicine-on-hi-tech-future-blue-background-for-wall"& _ 
                        "paper-template-web-design-vector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__11_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (11)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__11_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (11)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__12_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (12)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (2)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__2_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (2)3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__2_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (2)4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__4_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (4)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (5)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__5_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (5)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__6_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (6)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__6_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (6)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (7)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__7_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (7)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__9_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (9)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property istockphoto_2099370050_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("istockphoto-2099370050-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property istockphoto_2099370050_612x6121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("istockphoto-2099370050-612x6121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medical_icon_network_connection_with_modern_virtual_screen_interface_on_hospital_background_medicine_technology_network_concept_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medical-icon-network-connection-with-modern-virtual-screen-interface-on-hospital-"& _ 
                        "background-medicine-technology-network-concept-photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medical_icon_network_connection_with_modern_virtual_screen_interface_on_hospital_background_medicine_technology_network_concept_photo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medical-icon-network-connection-with-modern-virtual-screen-interface-on-hospital-"& _ 
                        "background-medicine-technology-network-concept-photo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medical_infographic_banner_background_clinic_pharmacy_laboratory_test_and_research_healthcare_concept_backdrop_illustration_vector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medical-infographic-banner-background-clinic-pharmacy-laboratory-test-and-researc"& _ 
                        "h-healthcare-concept-backdrop-illustration-vector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_empty_white_desk_with_blur_hospital_background_picture_image_15459449() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-empty-white-desk-with-blur-hospital-background-picture-image_15459449", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_empty_white_desk_with_blur_hospital_background_picture_image_154594491() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-empty-white-desk-with-blur-hospital-background-picture-image_154594491", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_empty_white_desk_with_blur_hospital_background_picture_image_154594492() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-empty-white-desk-with-blur-hospital-background-picture-image_154594492", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_simple_medical_doctor_doing_molecular_report_picture_image_955928() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-simple-medical-doctor-doing-molecular-report-picture-image_955928", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
